# Generated by Django 5.2.4 on 2025-08-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.IntegerField(max_length=6)),
            ],
        ),
    ]
