# Generated by Django 5.2.4 on 2025-08-18 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_registereduser_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegisteredUser',
        ),
    ]
